# dockerfile to build java image
# Version: 1.0.0 
FROM centos:centos7
MAINTAINER Afterqcd "afterqcd@gmail.com"
ADD jdk-8u91-linux-x64.tar.gz /usr/java/
ENV JAVA_HOME /usr/java/jdk1.8.0_91
ENV PATH $JAVA_HOME/bin:$PATH
